import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}${geistMono.variable} antialiased`}
      >
        {/* 2nd way to implement dark mode and light mode */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* here theme-inline dark or light mode background or foreground color pass */}
          <main className="bg-background text-foreground h-full">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
